mod "boxen",    "3.5.0", :github_tarball => "boxen/puppet-boxen"
mod "homebrew", "1.8.1", :github_tarball => "boxen/puppet-homebrew"
mod "stdlib",   "3.2.1", :github_tarball => "puppetlabs/puppetlabs-stdlib"
